spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=- 1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create

security:
  oauth2:
    resource.id: oauth2_application
access_token:
  validity_period: 3600
refresh_token:
  validity_period: 10000
